name: BrysonWilding
favicon: null
layout_spectrum: 0.5315636736340821
typography_spectrum: 0.09028731100261211
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.0074170168954879045
  lightness: 0.7312076045200229
  saturation: 0.55915925395675
  rhythmicContrast: 0.8257666225545108
purpose: []
